name: deploy to EC2

on:
  push:
    branches:
      - main

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: setupSSH
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
              env:
                HOST: ${{ secrets.HOST }}
            
            - name: Transfer files to EC2
              run: |
                rsync -avz --delete ./ ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/html/
              env:
                HOST: ${{ secrets.HOST }}
                USER: ${{ secrets.USER }}

            # - name: Restart Nginx (Optional)
            #   run: ssh ${{ secrets.USER }}@${{ secrets.HOST }} 'sudo systemctl restart nginx'
            #   env:
            #     HOST: ${{ secrets.HOST }}
            #     USER: ${{ secrets.USER }}

        